/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

export interface JobListing {
  company: string;
  title: string;
  location: string;
  description: string;
  type: string;
  industry: string;
}

export const belgianJobs: JobListing[] = [
  {
    company: 'UCB',
    title: 'Biostatistician',
    location: 'Braine-l\'Alleud, Walloon Region',
    description: 'Provide statistical expertise for the design, analysis, and interpretation of clinical trials.',
    type: 'Full-time',
    industry: 'Pharmaceuticals',
  },
  {
    company: 'Janssen Pharmaceutica',
    title: 'Senior Scientist, Immunology',
    location: 'Beerse, Flanders',
    description: 'Lead and contribute to drug discovery projects in the field of immunology.',
    type: 'Full-time',
    industry: 'Pharmaceuticals',
  },
  {
    company: 'BNP Paribas Fortis',
    title: 'IT Project Manager - Core Banking',
    location: 'Brussels',
    description: 'Manage and deliver complex IT projects within the core banking domain.',
    type: 'Full-time',
    industry: 'Banking',
  },
  {
    company: 'Delhaize Belgium',
    title: 'Category Manager - Fresh Products',
    location: 'Anderlecht, Brussels',
    description: 'Develop and implement category strategies for fresh products to drive sales and market share.',
    type: 'Full-time',
    industry: 'Retail',
  },
  {
    company: 'Solvay',
    title: 'R&I Process Engineer',
    location: 'Neder-Over-Heembeek, Brussels',
    description: 'Design, develop, and optimize chemical processes for new and existing products.',
    type: 'Full-time',
    industry: 'Chemicals',
  },
  {
    company: 'IMEC',
    title: 'PhD Researcher in Neuromorphic Computing',
    location: 'Leuven, Flanders',
    description: 'Conduct cutting-edge research on brain-inspired computing architectures.',
    type: 'Research',
    industry: 'Semiconductors',
  },
  {
    company: 'Colruyt Group',
    title: 'Data Engineer',
    location: 'Halle, Flanders',
    description: 'Build and maintain scalable data pipelines to support analytics and business intelligence.',
    type: 'Full-time',
    industry: 'Retail',
  },
  {
    company: 'KBC Bank & Verzekering',
    title: 'Cybersecurity Analyst',
    location: 'Brussels',
    description: 'Monitor, detect, and respond to cybersecurity threats to protect the bank\'s information systems.',
    type: 'Full-time',
    industry: 'Banking',
  },
  {
    company: 'Proximus',
    title: 'Fiber Network Planner',
    location: 'Multiple Locations, Belgium',
    description: 'Plan and design the expansion of the fiber optic network across Belgium.',
    type: 'Full-time',
    industry: 'Telecommunications',
  },
  {
    company: 'GSK',
    title: 'Quality Assurance Specialist - Vaccines',
    location: 'Wavre, Walloon Region',
    description: 'Ensure compliance with GMP and regulatory requirements for the production of vaccines.',
    type: 'Full-time',
    industry: 'Pharmaceuticals',
  },
  {
    company: 'Port of Antwerp-Bruges',
    title: 'Logistics Project Manager',
    location: 'Antwerp, Flanders',
    description: 'Manage projects aimed at optimizing logistics flows and improving operational efficiency.',
    type: 'Full-time',
    industry: 'Logistics',
  },
  {
    company: 'Audi Brussels',
    title: 'Automation Engineer - EV Production',
    location: 'Forest, Brussels',
    description: 'Develop and maintain automation systems for the production line of electric vehicles.',
    type: 'Full-time',
    industry: 'Automotive',
  },
  {
    company: 'Telenet',
    title: 'Product Owner - Digital TV',
    location: 'Mechelen, Flanders',
    description: 'Define the vision and roadmap for digital TV products, working closely with development teams.',
    type: 'Full-time',
    industry: 'Telecommunications',
  },
  {
    company: 'ING Belgium',
    title: 'Frontend Developer (React/Vue)',
    location: 'Brussels',
    description: 'Build modern and user-friendly web applications for online banking services.',
    type: 'Full-time',
    industry: 'Banking',
  },
  {
    company: 'Agfa-Gevaert',
    title: 'Software Engineer - Medical Imaging',
    location: 'Mortsel, Flanders',
    description: 'Develop software for medical imaging solutions, contributing to advancements in healthcare technology.',
    type: 'Full-time',
    industry: 'Healthcare Technology',
  },
  {
    company: 'Euroclear',
    title: 'Risk Management Officer',
    location: 'Brussels',
    description: 'Identify, assess, and mitigate financial and operational risks within a key financial market infrastructure.',
    type: 'Full-time',
    industry: 'Finance',
  },
  {
    company: 'Barco',
    title: 'Embedded Software Engineer',
    location: 'Kortrijk, Flanders',
    description: 'Design and develop embedded software for high-performance visualization solutions.',
    type: 'Full-time',
    industry: 'Technology',
  },
  {
    company: 'FOD Financiën - SPF Finances',
    title: 'Tax Inspector',
    location: 'Nationwide',
    description: 'Conduct audits and investigations to ensure compliance with Belgian tax laws.',
    type: 'Full-time',
    industry: 'Government',
  },
  {
    company: 'DEME Group',
    title: 'Offshore Wind Project Engineer',
    location: 'Zwijndrecht, Flanders',
    description: 'Provide engineering support for the construction and installation of offshore wind farms.',
    type: 'Full-time',
    industry: 'Energy',
  },
  {
    company: 'SWIFT',
    title: 'Information Security Architect',
    location: 'La Hulpe, Walloon Region',
    description: 'Design and implement robust security architectures to protect the global financial messaging network.',
    type: 'Full-time',
    industry: 'Finance',
  },
  {
    company: 'EY',
    title: 'Audit Associate',
    location: 'Diegem, Flanders',
    description: 'Perform financial audits for a diverse client portfolio, ensuring accuracy and compliance.',
    type: 'Full-time',
    industry: 'Consulting',
  },
  {
    company: 'Deloitte',
    title: 'M&A Consultant',
    location: 'Zaventem, Flanders',
    description: 'Advise clients on mergers and acquisitions, from strategy to post-merger integration.',
    type: 'Full-time',
    industry: 'Consulting',
  },
  {
    company: 'European Commission',
    title: 'Policy Officer - Digital Single Market',
    location: 'Brussels',
    description: 'Contribute to the development and implementation of EU policies related to digital services.',
    type: 'Contract',
    industry: 'Government',
  },
  {
    company: 'NATO',
    title: 'Cyber Defence Officer',
    location: 'Brussels',
    description: 'Protect NATO networks and systems from cyber threats through analysis and incident response.',
    type: 'Full-time',
    industry: 'Defence',
  },
  {
    company: 'Brussels Airlines',
    title: 'Cabin Crew Member',
    location: 'Zaventem, Flanders',
    description: 'Ensure the safety and comfort of passengers on board, providing excellent customer service.',
    type: 'Full-time',
    industry: 'Aviation',
  },
  {
    company: 'AB InBev',
    title: 'Global Brand Manager',
    location: 'Leuven, Flanders',
    description: 'Develop and execute global marketing strategies for one of our iconic beer brands.',
    type: 'Full-time',
    industry: 'FMCG',
  },
  {
    company: 'Pfizer',
    title: 'Regulatory Affairs Manager',
    location: 'Brussels',
    description: 'Manage regulatory submissions and ensure compliance with health authority regulations for new medicines.',
    type: 'Full-time',
    industry: 'Pharmaceuticals',
  },
  {
    company: 'Toyota Motor Europe',
    title: 'Hydrogen Powertrain Engineer',
    location: 'Zaventem, Flanders',
    description: 'Develop and test next-generation hydrogen fuel cell powertrain systems for future vehicles.',
    type: 'Full-time',
    industry: 'Automotive',
  },
  {
    company: 'Engie',
    title: 'Renewable Energy Project Developer',
    location: 'Brussels',
    description: 'Identify and develop new wind and solar energy projects from feasibility to financial close.',
    type: 'Full-time',
    industry: 'Energy',
  },
  {
    company: 'Besix',
    title: 'Civil Engineer - High-Rise Buildings',
    location: 'Brussels',
    description: 'Work on the design and construction of iconic high-rise building projects in Belgium and abroad.',
    type: 'Full-time',
    industry: 'Construction',
  },
  {
    company: 'LVMH',
    title: 'Retail Store Manager',
    location: 'Brussels',
    description: 'Lead a team to deliver exceptional customer experiences and drive sales for a luxury brand.',
    type: 'Full-time',
    industry: 'Luxury Goods',
  },
  {
    company: 'Egis',
    title: 'Transport Modeller',
    location: 'Brussels',
    description: 'Develop and apply transport models to assess mobility projects and policies.',
    type: 'Full-time',
    industry: 'Engineering',
  },
  {
    company: 'KU Leuven',
    title: 'Postdoctoral Researcher in AI Ethics',
    location: 'Leuven, Flanders',
    description: 'Conduct research on the ethical and societal implications of artificial intelligence.',
    type: 'Research',
    industry: 'Academia',
  },
  {
    company: 'VITO',
    title: 'Circular Economy Researcher',
    location: 'Mol, Flanders',
    description: 'Research and develop sustainable technologies and business models for a circular economy.',
    type: 'Research',
    industry: 'Sustainability',
  },
  {
    company: 'Bpost',
    title: 'E-commerce Logistics Coordinator',
    location: 'Neder-Over-Heembeek, Brussels',
    description: 'Manage and optimize the logistics process for e-commerce parcels from sorting to final delivery.',
    type: 'Full-time',
    industry: 'Logistics',
  },
  {
    company: 'Umicore',
    title: 'Materials Scientist - Battery Technology',
    location: 'Olen, Flanders',
    description: 'Develop next-generation cathode materials for rechargeable batteries used in electric vehicles.',
    type: 'Full-time',
    industry: 'Materials Science',
  },
  {
    company: 'SNCB/NMBS',
    title: 'Train Driver',
    location: 'Nationwide',
    description: 'Safely operate passenger trains on the Belgian national railway network.',
    type: 'Full-time',
    industry: 'Transportation',
  },
  {
    company: 'Fluxys',
    title: 'Gas Network Operations Engineer',
    location: 'Anderlecht, Brussels',
    description: 'Monitor and manage the Belgian high-pressure gas transmission network.',
    type: 'Full-time',
    industry: 'Energy',
  },
  {
    company: 'PwC',
    title: 'Technology Consultant - Salesforce',
    location: 'Brussels',
    description: 'Help clients transform their business by implementing and optimizing Salesforce solutions.',
    type: 'Full-time',
    industry: 'Consulting',
  },
  {
    company: 'Ageas',
    title: 'Actuarial Analyst',
    location: 'Brussels',
    description: 'Perform actuarial analysis, pricing, and reserving for life and non-life insurance products.',
    type: 'Full-time',
    industry: 'Insurance',
  },
  {
    company: 'Microsoft',
    title: 'Cloud Solution Architect',
    location: 'Zaventem, Flanders',
    description: 'Design and implement cloud solutions for enterprise customers on the Microsoft Azure platform.',
    type: 'Full-time',
    industry: 'Technology',
  },
  {
    company: 'Google',
    title: 'Account Manager, Large Customer Sales',
    location: 'Brussels',
    description: 'Manage relationships with large advertisers and help them achieve their marketing objectives with Google Ads.',
    type: 'Full-time',
    industry: 'Technology',
  },
  {
    company: 'Coca-Cola Europacific Partners',
    title: 'Supply Chain Planner',
    location: 'Anderlecht, Brussels',
    description: 'Plan and manage inventory levels and product flows to ensure optimal product availability.',
    type: 'Full-time',
    industry: 'FMCG',
  },
  {
    company: 'Cargill',
    title: 'Food Scientist',
    location: 'Vilvoorde, Flanders',
    description: 'Develop and innovate food ingredients and applications for the food and beverage industry.',
    type: 'Full-time',
    industry: 'Food Production',
  },
  {
    company: 'Cisco',
    title: 'Network Consulting Engineer',
    location: 'Diegem, Flanders',
    description: 'Provide technical expertise and consultancy to customers on Cisco networking solutions.',
    type: 'Full-time',
    industry: 'Technology',
  },
  {
    company: 'Elia',
    title: 'High Voltage Substation Engineer',
    location: 'Brussels',
    description: 'Manage the design, construction, and maintenance of high-voltage substations for the electricity grid.',
    type: 'Full-time',
    industry: 'Energy',
  },
  {
    company: 'Accenture',
    title: 'Digital Strategy Consultant',
    location: 'Brussels',
    description: 'Advise clients on digital transformation strategies to improve business performance.',
    type: 'Full-time',
    industry: 'Consulting',
  },
  {
    company: 'Amazon Web Services (AWS)',
    title: 'Solutions Architect',
    location: 'Brussels',
    description: 'Help customers design scalable, secure, and resilient cloud architectures on AWS.',
    type: 'Full-time',
    industry: 'Technology',
  },
  {
    company: 'VRT',
    title: 'Broadcast Journalist',
    location: 'Schaerbeek, Brussels',
    description: 'Research, write, and present news stories for the Flemish public broadcaster.',
    type: 'Full-time',
    industry: 'Media',
  },
  {
    company: 'Crelan',
    title: 'Credit Analyst',
    location: 'Anderlecht, Brussels',
    description: 'Assess the creditworthiness of loan applicants and make recommendations on credit decisions.',
    type: 'Full-time',
    industry: 'Banking',
  },
];
